default: &default
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    url: <%= ENV['DATABASE_URL'] %>

development:
    <<: *default
    database: turlink_be_development

test:
    <<: *default
    database: turlink_be_test

production:
    <<: *default
    database: turlink_be_production
    username: turlink_be
    password: <%= ENV["TURLINK_BE_DATABASE_PASSWORD"] %>
