# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

Tag.create(name: "javascript")
Tag.create(name: "react")
Tag.create(name: "ruby")
Tag.create(name: "rails")
Tag.create(name: "video")
Tag.create(name: "blog")
Tag.create(name: "tutorial")
Tag.create(name: "python")
Tag.create(name: "java")
Tag.create(name: "C#")
Tag.create(name: "conference talk")
Tag.create(name: "Angular")
Tag.create(name: "Vue.js")
Tag.create(name: "Django")
Tag.create(name: "Flask")
Tag.create(name: "Spring")
Tag.create(name: "Laravel")
Tag.create(name: "Express.js")
Tag.create(name: "next.js")
Tag.create(name: ".NET")
Tag.create(name: "Bootstrap")
Tag.create(name: "jQuery")
Tag.create(name: "TensorFlow")
Tag.create(name: "PyTorch")
Tag.create(name: "Node.js")
Tag.create(name: "testing")
Tag.create(name: "rspec")
Tag.create(name: "minitest")
Tag.create(name: "cypress")
Tag.create(name: "mocha")
Tag.create(name: "chai")
Tag.create(name: "Documentation")
Tag.create(name: "Tutorials")
Tag.create(name: "Courses")
Tag.create(name: "Code Samples")
Tag.create(name: "Books")
Tag.create(name: "Podcasts")
Tag.create(name: "Webinars")
Tag.create(name: "Cheat Sheets")
Tag.create(name: "Articles")
Tag.create(name: "Whitepapers")
Tag.create(name: "Tools")
Tag.create(name: "Reference Guides")
Tag.create(name: "Workshops")
Tag.create(name: "Object-Oriented Programming (OOP)")
Tag.create(name: "Functional Programming")
Tag.create(name: "Procedural Programming")
Tag.create(name: "Test-Driven Development (TDD)")
Tag.create(name: "Agile")
Tag.create(name: "DevOps")
Tag.create(name: "Microservices")
Tag.create(name: "RESTful APIs")
Tag.create(name: "Background Jobs")
Tag.create(name: "GraphQL")
Tag.create(name: "Serverless")
Tag.create(name: "SQL")
Tag.create(name: "NoSQL")
Tag.create(name: "PostgreSQL")
Tag.create(name: "MySQL")
Tag.create(name: "MongoDB")
Tag.create(name: "Redis")
Tag.create(name: "Firebase")
Tag.create(name: "SQLite")
Tag.create(name: "Oracle")
Tag.create(name: "Git")
Tag.create(name: "GitHub")
Tag.create(name: "GitLab")
Tag.create(name: "Bitbucket")
Tag.create(name: "SVN")
Tag.create(name: "AWS")
Tag.create(name: "Google Cloud")
Tag.create(name: "Azure")
Tag.create(name: "Heroku")
Tag.create(name: "DigitalOcean")
Tag.create(name: "Kubernetes")
Tag.create(name: "Docker")
Tag.create(name: "Render")
Tag.create(name: "Vercel")
Tag.create(name: "Fly.io")
Tag.create(name: "HTML")
Tag.create(name: "CSS")
Tag.create(name: "JavaScript")
Tag.create(name: "SASS/SCSS")
Tag.create(name: "Webpack")
Tag.create(name: "Gulp")
Tag.create(name: "Babel")
Tag.create(name: "Responsive Design")
Tag.create(name: "Authentication")
Tag.create(name: "Authorization")
Tag.create(name: "Middleware")
Tag.create(name: "WebSockets")
Tag.create(name: "Encryption")
Tag.create(name: "SSL/TLS")
Tag.create(name: "OAuth")
Tag.create(name: "JWT")
Tag.create(name: "Secure Coding Practices")
Tag.create(name: "Penetration Testing")
Tag.create(name: "Vulnerability Scanning")
Tag.create(name: "Unit Testing")
Tag.create(name: "Integration Testing")
Tag.create(name: "End-to-End Testing")
Tag.create(name: "Test Automation")
Tag.create(name: "Load Testing")
Tag.create(name: "Selenium")
Tag.create(name: "Jest")
Tag.create(name: "Scrum")
Tag.create(name: "Kanban")
Tag.create(name: "Jira")
Tag.create(name: "Trello")
Tag.create(name: "Asana")
Tag.create(name: "Time Tracking")
Tag.create(name: "Continuous Deployment")
Tag.create(name: "Continuous Integration")
Tag.create(name: "Jenkins")
Tag.create(name: "CircleCI")
Tag.create(name: "Travis CI")
Tag.create(name: "Ansible")
Tag.create(name: "Terraform")
Tag.create(name: "Design Patterns")
Tag.create(name: "SOLID Principles")
Tag.create(name: "Architecture")
Tag.create(name: "Domain-Driven Design (DDD)")
Tag.create(name: "Model-View-Controller (MVC)")
Tag.create(name: "Event-Driven Architecture")
Tag.create(name: "Monolithic Architecture")
Tag.create(name: "Clean Architecture")
Tag.create(name: "Neural Networks")
Tag.create(name: "Deep Learning")
Tag.create(name: "Natural Language Processing (NLP)")
Tag.create(name: "Computer Vision")
Tag.create(name: "AI Ethics")
Tag.create(name: "Model Training")
Tag.create(name: "Data Preprocessing")
Tag.create(name: "Model Evaluation")
Tag.create(name: "iOS Development")
Tag.create(name: "Android Development")
Tag.create(name: "Flutter")
Tag.create(name: "React Native")
Tag.create(name: "SwiftUI")
Tag.create(name: "Xamarin")
Tag.create(name: "Kotlin Multiplatform")
Tag.create(name: "IDEs")
Tag.create(name: "Text Editors")
Tag.create(name: "Command-Line Tools")
Tag.create(name: "Debugging Tools")
Tag.create(name: "Package Managers")
Tag.create(name: "npm")
Tag.create(name: "pip")
Tag.create(name: "bundler")
Tag.create(name: "Profiling Tools")
Tag.create(name: "Code Linters")
Tag.create(name: "REST")
Tag.create(name: "SOAP")
Tag.create(name: "JSON")
Tag.create(name: "XML")
Tag.create(name: "OpenAPI")
Tag.create(name: "gRPC")
Tag.create(name: "WebSocket")
Tag.create(name: "User Experience (UX)")
Tag.create(name: "User Interface (UI)")
Tag.create(name: "Wireframing")
Tag.create(name: "Prototyping")
Tag.create(name: "Figma")
Tag.create(name: "Sketch")
Tag.create(name: "Adobe XD")
Tag.create(name: "User Research")
Tag.create(name: "Open Source")
Tag.create(name: "Licensing")
Tag.create(name: "Ethics in Software Development")
Tag.create(name: "Software Maintenance")
Tag.create(name: "Code Review")
Tag.create(name: "Documentation Writing")